### ISSUE TITLE
自動隱藏過去賽程

### ISSUE THREAD

**Issue by Cypresslin** [nthspace/universiade#1]
是否能夠加入自動折疊過去賽程的功能呢？
（可以提示使用者「展開過去賽程」這樣）
因為隨著時間推移，使用者就得往下捲動更遠才能看到今日賽程以及售票按鈕
謝謝

**Comment by WendellLiu** [comment]
嗨，針對這點，目前以下方方式解決：

假設某項目有8/20, 8/21, 8/22 ... 8/30 這些天的賽事，且使用者當下的日期是8/24
會排序為： 8/24, 8/25 ... 8/30 8/20 ... 8/23
也就是將沒有過期的分為一組排在前面，已過期的則放在最後
組內的排序則與原本一樣由時間最早排至最晚

希望能解決你的問題，謝謝。
